#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-eigenbase-properties
Version  : 1.1.5
Release  : 2
URL      : https://github.com/julianhyde/eigenbase-properties/archive/eigenbase-properties-1.1.5.tar.gz
Source0  : https://github.com/julianhyde/eigenbase-properties/archive/eigenbase-properties-1.1.5.tar.gz
Source1  : https://repo1.maven.org/maven2/net/hydromatic/eigenbase-properties/1.1.5/eigenbase-properties-1.1.5.jar
Source2  : https://repo1.maven.org/maven2/net/hydromatic/eigenbase-properties/1.1.5/eigenbase-properties-1.1.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-eigenbase-properties-data = %{version}-%{release}

%description
[![Build Status](https://travis-ci.org/julianhyde/eigenbase-properties.png)](https://travis-ci.org/julianhyde/eigenbase-properties)

%package data
Summary: data components for the mvn-eigenbase-properties package.
Group: Data

%description data
data components for the mvn-eigenbase-properties package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5/eigenbase-properties-1.1.5.jar
/usr/share/java/.m2/repository/net/hydromatic/eigenbase-properties/1.1.5/eigenbase-properties-1.1.5.pom
